name: deploy-client

on:
  push:
    # watch for pull request into main branch
    branches:
      - main

    # watch for changes in client folder
    paths:
      - "client/**"
      - "trigger-deploy.txt"
env:
  applicationfolder: spring-boot-hello-world-example
  AWS_REGION: ap-southeast-2
  S3BUCKET: 1fs20z9y59rkp 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
    permissions:
      id-token: write
      contents: read

      # # build an image
      # - run: cd client && docker build -t thasup/client .

      # # login on docker hub
      # - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

       - name: Upload Artifact to s3
        working-directory: ${{ env.applicationfolder }}/target
        run: aws s3 cp *.war s3://${{ env.S3BUCKET }}/

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          role-session-name: GitHub-Action-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: chmod
        run: chmod -R +x ./.github

      - name: Build and Package Maven
        id: package
        working-directory: ${{ env.applicationfolder }}
        run: $GITHUB_WORKSPACE/.github/workflows/build.sh

      # # push an image to docker hub
      # - run: docker push thasup/client

      # # use and cliententicate doctl
      # - uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN}}

      # # give credential to k8s cluster
      # - run: doctl kubernetes cluster kubeconfig save aurapan-do-cluster

      # # restart deployment
      # - run: kubectl rollout restart deployment client-depl
